name = "vegasherobet-ch"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=vegasherobet.ch"
HMAC_KEY = "885c353211cc02f2044dfa3686e3e16752069305526db6c636124d78db146fa8"
COOKIE_NAME = "b6p"
PLAY_PATH = "explore"
BUTTON_ID = "p257d0d50ab38de6317984b4ee173535d"
GATE_SALT = "905a0b5700ade2c0"
